name: windows

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  windows_msvc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [x86, amd64]
        os: [windows-2022, windows-2025]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        
    - uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: ${{ matrix.platform }}

    - uses: seanmiddleditch/gha-setup-ninja@v6
      with:
        version: 1.12.1
        
    - name: Build GamespySDK
      run: |
        cmake --workflow --preset win
